version: '3'

services:
  mirai:
    build: .
    # 如果使用已构建的镜像，取消下面的注释并注释掉 build
    # image: sdjnmxd/overflow:latest
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./plugins:/app/plugins
    environment:
      # Java 配置
      - JAVA_OPTS=${JAVA_OPTS:--Xms512M -Xmx1G}
      # 时区配置
      - TZ=${TZ:-Asia/Shanghai}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  data:
    driver: local
  config:
    driver: local
  plugins:
    driver: local 