name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch:
    inputs:
      force_update:
        description: '强制更新 Docker Hub 描述'
        type: boolean
        default: false
        required: true

jobs:
  check-and-update:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if README.md changed
        id: check
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.force_update }}" == "true" ]; then
              echo "should_update=true" >> $GITHUB_OUTPUT
              echo "Manual trigger with force update, will update description"
            else
              echo "should_update=false" >> $GITHUB_OUTPUT
              echo "Manual trigger without force update, skipping update"
            fi
          else
            # 检查 README.md 是否有实际变化
            if git diff --quiet HEAD^ HEAD README.md; then
              echo "should_update=false" >> $GITHUB_OUTPUT
              echo "No changes in README.md, skipping update"
            else
              echo "should_update=true" >> $GITHUB_OUTPUT
              echo "README.md changed, will update description"
            fi
          fi

      - name: Update Docker Hub Description
        if: steps.check.outputs.should_update == 'true'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/overflow
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true 